     ORG 800H
	 LXI H,OUT_START
	 RST 3
	 JMP START
DODAJ
ODEJMIJ
NEGUJ
ZNAK
START
	 HLT
OUT_ENTR    DB 10,13,'@'
OUT_HASH1    DB '############@'
OUT_START 	 DB '##############'10,13,'# KALKULATOR #'10,13,'##############@'
OUT_FINF0    DB 10,13,'## OPERACJE ##',10,13,'@'
OUT_FINF1    DB '  (+) DODAJ',10,13,'  (-) ODEJMIJ',10,13,'  (n) NEGUJ@'
OUT_BSIGN    DB 10,13,'# NIE ROZPOZNANO ZNAKU #@'
IN_FNSIGN 	 DB 10,13,'> PODAJ ZNAK OPERACJI: @'
IN_OP1INF	 DB 10,13,'> OPERAND 1(HEKSADECYMALNIE): @'
IN_OP2INF	 DB 10,13,'> OPERAND 2(HEKSADECYMALNIE): @'
OUT_DINFO    DB 10,13,'## DODAWANIE ##@'
OUT_OINFO    DB 10,13,'## ODEJMOWANIE ##@'
OUT_NINFO    DB 10,13,'## NEGOWANIE ##@'
OUT_ENOP1    DB 10,13,'PODANY OPERAND 1: @'
OUT_ENOP2    DB 10,13,'PODANY OPERAND 2: @'
OUT_WYNIK    DB ' <--- WYNIK OPERACJI ##@'